"""
Project-wide settings: paths, the freeze date, and the series used.

Every stage imports from here, so a path or a series list is defined once.
Paths are built from the location of this file, so the code runs the same
from the repository root, from code/, on a Mac or on Nuvolos.
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[1]   # repository root

DATA_RAW = ROOT / "data" / "raw"               # stage 1 output, never edited by hand
DATA_PROCESSED = ROOT / "data" / "processed"   # stage 2+ outputs, regenerated by code
MANIFEST = ROOT / "data" / "manifest.json"     # fingerprints of the raw download
FIGURES = ROOT / "figures"                     # every figure in the paper
TABLES = ROOT / "tables"                       # every table in the paper

# ---------------------------------------------------------------------------
# Reproducibility
# ---------------------------------------------------------------------------
FREEZE_DATE = "2026-09-28"  # all data "as known on" this date; must be in the past
OBS_START = "2000-01-01"    # history before the sample, for 12-month changes
RANDOM_SEED = 42            # used by every model with a random component

# ---------------------------------------------------------------------------
# Series
# ---------------------------------------------------------------------------
PUBLIC = "US government source - public domain (verify on the FRED series page)"
THIRD_PARTY = "Third-party copyright - do not redistribute; regenerate with this script"

# Macro variables that DEFINE the regimes: series_id -> (block, description, licence, redistributable)
MACRO_SERIES = {
    "INDPRO":   ("growth",    "Industrial Production Index",                 PUBLIC, True),
    "TCU":      ("growth",    "Capacity Utilization: Total Industry",        PUBLIC, True),
    "RRSFS":    ("growth",    "Advance Real Retail and Food Services Sales", PUBLIC, True),
    "HOUST":    ("growth",    "Housing Starts: Total",                       PUBLIC, True),
    "PAYEMS":   ("labour",    "All Employees, Total Nonfarm",                PUBLIC, True),
    "UNRATE":   ("labour",    "Unemployment Rate",                           PUBLIC, True),
    "ICSA":     ("labour",    "Initial Claims (weekly; vintages only from 2009)", PUBLIC, True),
    "CPIAUCSL": ("inflation", "CPI, All Items",                              PUBLIC, True),
    "CPILFESL": ("inflation", "CPI, Less Food and Energy (core)",            PUBLIC, True),
    "PPIACO":   ("inflation", "PPI, All Commodities",                        PUBLIC, True),
}

# Market-based variables: NOT used to define regimes (circularity), descriptive only.
MARKET_SERIES = {
    "T10Y2Y": ("market", "10Y minus 2Y Treasury spread",           PUBLIC, True),
    "BAA10Y": ("market", "Moody's Baa yield minus 10Y Treasury",   THIRD_PARTY, False),
    "NFCI":   ("market", "Chicago Fed National Financial Conditions Index",
               "Federal Reserve Bank of Chicago - verify terms before redistributing", False),
}

# SPY US equities, TLT long Treasuries, GLD gold, DBC broad commodities.
ETF_TICKERS = ["SPY", "TLT", "GLD", "DBC"]
